### ISSUE TITLE
what is num_fac in create_mclp_cc_model function?

### ISSUE THREAD

**Issue by wsy0929sky** [apulverizer/pyspatialopt#6]
HI, this is really good repo! Many thanks

But I could't understand what is num_fac used for  ?
can you provide a data  example of num_fac ?

**Comment by apulverizer** [comment]
It is a dictionary that defines how many types of facilities should be sited:

An example might be I need to allocate 10 level-1 trauma centers and 15 level-2 trauma centers. So for MCLP the model would ensure 25 total facilities (10 of which are level 1 and 15 of which are level 2) are allocated.

```python
num_fac = {
    "trauma_level_1": 10,
    "trauma_level_2": 15
}
```

If you don't care about specific types, you can just use it like:

```python
num_fac = {
    "total": 25
}
```

This is how it is used in the following example:
https://github.com/apulverizer/pyspatialopt/blob/master/examples/binary_mclp_qgis.py#L47

**Comment by wsy0929sky** [comment]
Great explanation! Thanks
